In [10]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [4]:
from termcolor import colored
import numpy as np
import os, errno
import pandas as pd
from natsort import natsorted

In [5]:
# Display pandas df without truncation
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [7]:
main_folder = os.getcwd()
main_folder

'/home/luigi/Documents/ARGoS/argos-LMCRW-script'

In [8]:
data_folder = os.path.join(main_folder, "results", "JAN_2023")
data_folder

'/home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023'

In [9]:
if not os.path.exists(data_folder):
    print(colored(f"ERROR! folder {data_folder} does not exists", 'red'))
else:
    print(colored(f"OK folder {data_folder} exists", 'green'))

OK folder /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023 exists


In [44]:
def get_robotDf_label(numRobot):
    fieldsPerRobot = 5
    robotPos_label = ['time']
    for i in range(0, numRobot * fieldsPerRobot, fieldsPerRobot):
        robotPos_label += ['id' + str(i // fieldsPerRobot),
                           'posx' + str(i // fieldsPerRobot),
                           'posy' + str(i // fieldsPerRobot),
                           'ori' + str(i // fieldsPerRobot),
                           'state' + str(i // fieldsPerRobot)]
    return robotPos_label

In [45]:
def get_robotPos_label(numRobot):
    fieldsPerRobot = 2
    robotPos_label = []
    for i in range(0, numRobot * fieldsPerRobot, fieldsPerRobot):
        robotPos_label += ['posx' + str(i // fieldsPerRobot),
                           'posy' + str(i // fieldsPerRobot)]
    return robotPos_label

In [46]:
get_robotDf_label(4)

['time',
 'id0',
 'posx0',
 'posy0',
 'ori0',
 'state0',
 'id1',
 'posx1',
 'posy1',
 'ori1',
 'state1',
 'id2',
 'posx2',
 'posy2',
 'ori2',
 'state2',
 'id3',
 'posx3',
 'posy3',
 'ori3',
 'state3']

In [47]:
get_robotPos_label(4)

['posx0', 'posy0', 'posx1', 'posy1', 'posx2', 'posy2', 'posx3', 'posy3']

In [203]:
# experiment = 'simple_experiment'
# experiment = 'open_space'
# experiment = 'open_space_target100cm'
# experiment = 'random_angle'
experiment = 'bouncing_angle'

In [204]:
for dirName, subdirList, fileList in os.walk(os.path.join(data_folder, "Simulated", experiment)):
        if '1800' not in dirName:
            continue
            
        print(colored("DirName:", 'blue'), dirName)
        n_robots = int(dirName.split('/')[-1].split('_')[1].split('#')[-1])
        print(f"Num robots: {n_robots}")
        
        np_concatenatedPos = np.array([])
        for fileName in natsorted(fileList):
            if fileName.endswith('kiloLOG.txt'):
                
                # print(colored("\tfileName:", 'blue'), fileName)
                if not os.path.getsize(os.path.join(dirName, fileName)) > 0:
                    print("Error, empty file at:" + os.path.join(fileList, fileName))
                    continue
                

                df_single = pd.read_csv(os.path.join(dirName, fileName), sep="\t", header=None)
                df_single = df_single.dropna(axis=1)
                df_single.columns = get_robotDf_label(n_robots)
                
                np_pos = df_single[get_robotPos_label(n_robots)].values
                
                np_concatenatedPos = np.column_stack((np_concatenatedPos, np_pos)) if np_concatenatedPos.size else np_pos
                # print(f"\tnp_concatenatedPos shape {np_concatenatedPos.shape}")
                
        
        
        directory = os.path.join(data_folder, "pos_pkl", "Simulated", experiment)
        if not os.path.exists(directory):
            print(colored(f"Mkdir folder {directory}", 'green'))
            os.makedirs(directory)
        
        storagePath=os.path.join(directory, dirName.split('/')[-1]+'.npy')
        
        reshape_concatenated = np_concatenatedPos.reshape(np_concatenatedPos.shape[0], -1, 2)
#         print(f"reshape_concatenated shape: {reshape_concatenated.shape}")
        
        print(f"Saving concatenated positions at: {storagePath}")
        with open(storagePath, 'wb') as f:
            np.save(f, reshape_concatenated)
            
        

DirName: /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/Simulated/bouncing_angle/2022-12-06_robots#100_alpha#1.4_rho#0.9_1800
Num robots: 100
Mkdir folder /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/pos_pkl/Simulated/bouncing_angle
Saving concatenated positions at: /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/pos_pkl/Simulated/bouncing_angle/2022-12-06_robots#100_alpha#1.4_rho#0.9_1800.npy
DirName: /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/Simulated/bouncing_angle/2022-12-06_robots#100_alpha#1.8_rho#0.0_1800
Num robots: 100
Saving concatenated positions at: /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/pos_pkl/Simulated/bouncing_angle/2022-12-06_robots#100_alpha#1.8_rho#0.0_1800.npy
DirName: /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/Simulated/bouncing_angle/2022-12-06_robots#10_alpha#2.0_rho#0.9_1800
Num robots: 10
Saving concatenated positions at: /home/luigi/Documents

Saving concatenated positions at: /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/pos_pkl/Simulated/bouncing_angle/2022-12-06_robots#20_alpha#1.4_rho#0.3_1800.npy
DirName: /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/Simulated/bouncing_angle/2022-12-06_robots#50_alpha#1.8_rho#0.3_1800
Num robots: 50
Saving concatenated positions at: /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/pos_pkl/Simulated/bouncing_angle/2022-12-06_robots#50_alpha#1.8_rho#0.3_1800.npy
DirName: /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/Simulated/bouncing_angle/2022-12-06_robots#20_alpha#1.8_rho#0.6_1800
Num robots: 20
Saving concatenated positions at: /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/pos_pkl/Simulated/bouncing_angle/2022-12-06_robots#20_alpha#1.8_rho#0.6_1800.npy
DirName: /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/Simulated/bouncing_angle/2022-12-06_robots#100_alpha#1.2_rho#0.3_1800
Num ro

Saving concatenated positions at: /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/pos_pkl/Simulated/bouncing_angle/2022-12-06_robots#20_alpha#1.2_rho#0.9_1800.npy
DirName: /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/Simulated/bouncing_angle/2022-12-06_robots#100_alpha#1.8_rho#0.3_1800
Num robots: 100
Saving concatenated positions at: /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/pos_pkl/Simulated/bouncing_angle/2022-12-06_robots#100_alpha#1.8_rho#0.3_1800.npy
DirName: /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/Simulated/bouncing_angle/2022-12-06_robots#10_alpha#1.6_rho#0.6_1800
Num robots: 10
Saving concatenated positions at: /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/pos_pkl/Simulated/bouncing_angle/2022-12-06_robots#10_alpha#1.6_rho#0.6_1800.npy
DirName: /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/Simulated/bouncing_angle/2022-12-06_robots#50_alpha#2.0_rho#0.9_1800
Num 

Saving concatenated positions at: /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/pos_pkl/Simulated/bouncing_angle/2022-12-06_robots#100_alpha#1.8_rho#0.6_1800.npy
DirName: /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/Simulated/bouncing_angle/2022-12-06_robots#10_alpha#1.4_rho#0.0_1800
Num robots: 10
Saving concatenated positions at: /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/pos_pkl/Simulated/bouncing_angle/2022-12-06_robots#10_alpha#1.4_rho#0.0_1800.npy
DirName: /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/Simulated/bouncing_angle/2022-12-06_robots#20_alpha#1.4_rho#0.9_1800
Num robots: 20
Saving concatenated positions at: /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/pos_pkl/Simulated/bouncing_angle/2022-12-06_robots#20_alpha#1.4_rho#0.9_1800.npy
DirName: /home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/Simulated/bouncing_angle/2022-12-06_robots#100_alpha#1.6_rho#0.3_1800
Num r

In [155]:
directory

'/home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/pos_pkl/Simulated/random_angle'

In [157]:
temp_dir = '/home/luigi/Documents/ARGoS/argos-LMCRW-script/results/JAN_2023/pos_pkl/Simulated/baseline'

In [158]:
temp_file = 'baseline_2021-10-13_robots#1_alpha#1.2_rho#0.0_baseline_1800simulated_pos.npy'

In [159]:
file_Path = os.path.join(temp_dir, temp_file)

In [160]:
with open(file_Path, 'rb') as f:
    boh = np.load(f)

In [161]:
boh.shape

(181, 500, 2)

In [178]:
boh[:3, :4, :]

array([[[-0.003, -0.011],
        [ 0.   , -0.003],
        [ 0.01 ,  0.004],
        [ 0.001, -0.002]],

       [[ 0.007, -0.077],
        [-0.001,  0.006],
        [-0.045, -0.016],
        [-0.068,  0.049]],

       [[-0.041, -0.163],
        [-0.053,  0.046],
        [-0.046, -0.081],
        [-0.123,  0.006]]])

In [181]:
boh1 = boh[:3, :4, :]

In [182]:
boh1.shape

(3, 4, 2)

In [184]:
boh1.reshape(boh1.shape[0], -1)

array([[-0.003, -0.011,  0.   , -0.003,  0.01 ,  0.004,  0.001, -0.002],
       [ 0.007, -0.077, -0.001,  0.006, -0.045, -0.016, -0.068,  0.049],
       [-0.041, -0.163, -0.053,  0.046, -0.046, -0.081, -0.123,  0.006]])

In [188]:
np_concatenatedPos.shape

(181, 10000)

In [191]:
np_concatenatedPos[:3,:6]

array([[ 0.0637, -0.1603, -0.3212,  0.1757,  0.3731, -0.0616],
       [ 0.1052, -0.165 , -0.346 ,  0.2455,  0.3382,  0.0279],
       [ 0.1378, -0.0822, -0.2658,  0.233 ,  0.3945,  0.1086]])

In [193]:
temp1 = np_concatenatedPos[:3,:6]
temp1 = temp1.reshape(temp1.shape[0], -1, 2)
temp1.shape

(3, 3, 2)